apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ragframework.fullname" . }}-{{ .Values.api.name }}
  labels:
    {{- include "ragframework.api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "ragframework.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "ragframework.api.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ragframework.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.securityContext | nindent 8 }}
      containers:
      - name: {{ .Values.api.name }}
        image: {{ include "ragframework.api.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.api.service.targetPort }}
          protocol: TCP
        env:
        {{- range $key, $value := .Values.api.env }}
        - name: {{ $key }}
          {{- if kindIs "map" $value }}
          valueFrom:
            {{- if $value.secretKeyRef }}
            secretKeyRef:
              name: {{ $value.secretKeyRef.name }}
              key: {{ $value.secretKeyRef.key }}
            {{- else if $value.configMapKeyRef }}
            configMapKeyRef:
              name: {{ $value.configMapKeyRef.name }}
              key: {{ $value.configMapKeyRef.key }}
            {{- else if $value.fieldRef }}
            fieldRef:
              fieldPath: {{ $value.fieldRef.fieldPath }}
            {{- end }}
          {{- else }}
          value: {{ $value | quote }}
          {{- end }}
        {{- end }}
        {{- with .Values.api.envFrom }}
        envFrom:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        livenessProbe:
          {{- toYaml .Values.api.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.api.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.api.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
